import React, { useState } from 'react';
import { Globe, Copy, Check, ShieldCheck, Download, Code } from 'lucide-react';

const SL = {
  fontSize: 11, fontWeight: 700, letterSpacing: '0.07em', textTransform: 'uppercase', color: '#676879', marginBottom: 12
};

export default function MetaRobotsTool() {
  const [tab, setTab] = useState('meta'); // meta, robots
  const [title, setTitle] = useState('Pahruli — 60 Offline Tools for Founders & Creators');
  const [desc, setDesc] = useState('60 instant, zero-signup utilities: PDF Suite, Image Resizer, SQL Dev Tools, & Fee Calculators. 100% client-side privacy.');
  const [url, setUrl] = useState('https://pahruli.com/');
  const [imgUrl, setImgUrl] = useState('https://pahruli.com/og-image.jpg');
  const [robotsIndex, setRobotsIndex] = useState('index, follow');
  const [copied, setCopied] = useState(false);

  // Robots.txt state
  const [disallowAdmin, setDisallowAdmin] = useState(true);
  const [disallowTmp, setDisallowTmp] = useState(true);
  const [sitemapUrl, setSitemapUrl] = useState('https://pahruli.com/sitemap.xml');

  const metaHtml = `<!-- Primary SEO Tags -->
<title>${title}</title>
<meta name="description" content="${desc}" />
<meta name="robots" content="${robotsIndex}" />
<link rel="canonical" href="${url}" />

<!-- OpenGraph / LinkedIn / Facebook -->
<meta property="og:type" content="website" />
<meta property="og:url" content="${url}" />
<meta property="og:title" content="${title}" />
<meta property="og:description" content="${desc}" />
<meta property="og:image" content="${imgUrl}" />

<!-- Twitter Card -->
<meta name="twitter:card" content="summary_large_image" />
<meta name="twitter:url" content="${url}" />
<meta name="twitter:title" content="${title}" />
<meta name="twitter:description" content="${desc}" />
<meta name="twitter:image" content="${imgUrl}" />`;

  const robotsTxt = `# robots.txt generated by Pahruli
User-agent: *
${disallowAdmin ? 'Disallow: /admin/\nDisallow: /api/' : ''}
${disallowTmp ? 'Disallow: /tmp/\nDisallow: /private/' : ''}
Allow: /

Sitemap: ${sitemapUrl}`;

  const currentCode = tab === 'meta' ? metaHtml : robotsTxt;

  const handleCopy = () => {
    navigator.clipboard.writeText(currentCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadRobots = () => {
    const blob = new Blob([robotsTxt], { type: 'text/plain;charset=utf-8' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'robots.txt';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
  };

  return (
    <div className="space-y-6">
      <div className="p-5 rounded-2xl bg-[#eceeff] border border-[#d5d9fc] flex items-start gap-3 mb-6">
        <ShieldCheck className="text-[#6161ff] shrink-0 mt-0.5" size={20} />
        <div>
          <h4 style={{ fontSize: 14, fontWeight: 700, color: '#1f2532' }}>
            100% Client-Side Meta Tag & Robots.txt Generator
          </h4>
          <p style={{ fontSize: 13, color: '#676879', marginTop: 2 }}>
            "Build production SEO title tags, OpenGraph cards, Twitter preview cards, and custom robots.txt crawl rules instantly."
          </p>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-[#e6e9ef] mb-8">
        <button
          onClick={() => setTab('meta')}
          className={`px-6 py-3 font-bold text-sm border-b-2 transition ${
            tab === 'meta'
              ? 'border-[#6161ff] text-[#6161ff]'
              : 'border-transparent text-[#676879] hover:text-[#1f2532]'
          }`}
        >
          SEO Meta & OpenGraph Tags
        </button>
        <button
          onClick={() => setTab('robots')}
          className={`px-6 py-3 font-bold text-sm border-b-2 transition ${
            tab === 'robots'
              ? 'border-[#6161ff] text-[#6161ff]'
              : 'border-transparent text-[#676879] hover:text-[#1f2532]'
          }`}
        >
          Robots.txt Generator
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {tab === 'meta' ? (
          <div className="space-y-4">
            <div>
              <div style={SL}>Page Title ({title.length} chars)</div>
              <input
                type="text"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                className="w-full h-11 px-3 rounded-lg border border-[#d0d4e4] text-sm font-bold text-[#1f2532]"
              />
              <span className="text-xs text-[#868894]">Recommended: 50–60 characters</span>
            </div>

            <div>
              <div style={SL}>Meta Description ({desc.length} chars)</div>
              <textarea
                value={desc}
                onChange={(e) => setDesc(e.target.value)}
                rows={3}
                className="w-full p-3 rounded-lg border border-[#d0d4e4] text-sm text-[#1f2532]"
              />
              <span className="text-xs text-[#868894]">Recommended: 120–160 characters</span>
            </div>

            <div>
              <div style={SL}>Canonical & OpenGraph URL</div>
              <input
                type="text"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                className="w-full h-11 px-3 rounded-lg border border-[#d0d4e4] text-sm font-mono text-[#1f2532]"
              />
            </div>

            <div>
              <div style={SL}>Social Card Banner Image URL</div>
              <input
                type="text"
                value={imgUrl}
                onChange={(e) => setImgUrl(e.target.value)}
                className="w-full h-11 px-3 rounded-lg border border-[#d0d4e4] text-sm font-mono text-[#1f2532]"
              />
            </div>

            <div>
              <div style={SL}>Search Engine Indexing Rule</div>
              <select
                value={robotsIndex}
                onChange={(e) => setRobotsIndex(e.target.value)}
                className="w-full h-11 px-3 rounded-lg border border-[#d0d4e4] text-sm font-bold text-[#1f2532] bg-white"
              >
                <option value="index, follow">index, follow (Allow Indexing & Links)</option>
                <option value="noindex, nofollow">noindex, nofollow (Hide from Google)</option>
                <option value="index, nofollow">index, nofollow (Index page, do not follow links)</option>
              </select>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div>
              <div style={SL}>Sitemap URL</div>
              <input
                type="text"
                value={sitemapUrl}
                onChange={(e) => setSitemapUrl(e.target.value)}
                className="w-full h-11 px-3 rounded-lg border border-[#d0d4e4] text-sm font-mono text-[#1f2532]"
              />
            </div>

            <div className="space-y-3 pt-2">
              <div style={SL}>Crawl Disallow Rules</div>
              <label className="flex items-center gap-2 text-sm font-semibold text-[#1f2532] cursor-pointer">
                <input
                  type="checkbox"
                  checked={disallowAdmin}
                  onChange={(e) => setDisallowAdmin(e.target.checked)}
                  className="accent-[#6161ff] w-4 h-4"
                />
                Disallow /admin/ and /api/ paths
              </label>
              <label className="flex items-center gap-2 text-sm font-semibold text-[#1f2532] cursor-pointer">
                <input
                  type="checkbox"
                  checked={disallowTmp}
                  onChange={(e) => setDisallowTmp(e.target.checked)}
                  className="accent-[#6161ff] w-4 h-4"
                />
                Disallow /tmp/ and /private/ directories
              </label>
            </div>
          </div>
        )}

        <div>
          <div className="flex items-center justify-between mb-2">
            <span style={SL}>Generated Code Output</span>
            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1 rounded-lg bg-[#6161ff] text-white text-xs font-bold hover:bg-[#4e4ee0]"
              >
                {copied ? <Check size={14} /> : <Copy size={14} />}
                {copied ? 'Copied!' : 'Copy Code'}
              </button>
              {tab === 'robots' && (
                <button
                  onClick={handleDownloadRobots}
                  className="flex items-center gap-1.5 px-3 py-1 rounded-lg border border-[#6161ff] text-[#6161ff] text-xs font-bold hover:bg-[#eceeff]"
                >
                  <Download size={14} />
                  Download robots.txt
                </button>
              )}
            </div>
          </div>
          <textarea
            value={currentCode}
            readOnly
            rows={16}
            className="w-full p-4 rounded-xl border border-[#d0d4e4] font-mono text-xs text-[#1f2532] bg-[#fbfbfc] focus:outline-none"
          />
        </div>
      </div>
    </div>
  );
}
